name: trpb_protein
model:
  _target_: problem.basic.XOR
  ratio: 0.5
  length: 389

data:
  _target_: data.protein.ProteinPredictorDataset
  data_config:
    data_path: data/fitness.csv
    full_seq: MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLRDYAGRPTPLYFARRLSEKYGARVYLKREDLLHTGAHKINNAIGQVLLAKLMGKTRIIAETGAGQHGVATATAAALFGMECVIYMGEEDTIRQKLNVERMKLLGAKVVPVKSGSRTLKDAIDEALRDWITNLQTTYYVFGSVVGPHPYPIIVRNFQKVIGEETKKQIPEKEGRLPDYIVACVSGGSNAAGIFYPFIDSGVKLIGVEAGGEGLETGKHAASLLKGKIGYLHGSKTFVLQDDWGQVQVSHSVSAGLDYSGVGPEHAYWRETGKVLYDAVTDEEALDAFIELSRLEGIIPALESSHALAYLKKINIKGKVVVVNLSGRGDKDLESVLNHPYVRERIR
    seq_len: 389
    residues: [183, 184, 227, 228] #mutated positions, this uses 1 indexing
    # tokenizer: #use the one from evodiff
    n_samples: 100000
    seed: 42
    alphabet_size: 26
exp_dir: exps/protein

